# Generated by Django 2.1.3 on 2019-05-19 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='last_seen',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportpost',
            name='photo',
            field=models.ImageField(default='default', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='posted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
