# Generated by Django 2.1.3 on 2019-05-19 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0002_auto_20190519_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='last_seen',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
