# Generated by Django 2.1.3 on 2019-05-19 19:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snoop', '0004_auto_20190519_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SawPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('photo', models.ImageField(upload_to='imagesunknown/')),
                ('last_seen', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('details', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2019, 5, 19, 19, 13, 35, 382340, tzinfo=utc), editable=False)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 19, 13, 35, 164874, tzinfo=utc), editable=False),
        ),
    ]
