# Generated by Django 2.1.3 on 2019-05-21 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0005_auto_20190520_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 14, 32, 45, 680651, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='sawpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 14, 32, 45, 919018, tzinfo=utc), editable=False),
        ),
    ]
