# Generated by Django 2.1.3 on 2019-05-21 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0006_auto_20190521_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 18, 46, 22, 62267, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='sawpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 18, 46, 22, 300631, tzinfo=utc), editable=False),
        ),
    ]
