# Generated by Django 2.1.3 on 2019-05-22 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0008_auto_20190522_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 16, 20, 34, 614391, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='sawpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 16, 20, 34, 866712, tzinfo=utc), editable=False),
        ),
    ]
