# Generated by Django 2.1.3 on 2019-05-25 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0009_auto_20190522_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 25, 7, 29, 47, 983269, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='sawpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 25, 7, 29, 48, 237588, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='sawpost',
            name='details',
            field=models.TextField(default='N/A'),
        ),
    ]
