# Generated by Django 2.1.3 on 2019-05-25 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snoop', '0010_auto_20190525_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 25, 7, 30, 30, 78767, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='details',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='sawpost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 25, 7, 30, 30, 313140, tzinfo=utc), editable=False),
        ),
    ]
